-- 景区游客消费数据集
CREATE TABLE IF NOT EXISTS dwd.dwd_ord_attraction_ticket_order_di (
  order_no                 STRING COMMENT '订单编号',
  traveler_id              STRING COMMENT '游客ID',
  trip_no                  STRING COMMENT '行程编号',
  attraction_id            STRING COMMENT '景区ID（携程景区POI编号）',
  attraction_name          STRING COMMENT '景区名称',
  attraction_province_name STRING COMMENT '景区所在省份（由商品文本推断）',
  attraction_city_name     STRING COMMENT '景区所在城市（由商品文本推断）',
  attraction_category_type BIGINT COMMENT '景区类别编码：1-主题乐园 2-动物园/海洋馆 3-博物馆/展馆 4-演艺/秀场 5-温泉度假 6-古镇古村 7-宗教寺观 8-历史遗迹 9-滨海海岛 10-湖泊水域 11-山岳峡谷 12-自然生态 13-城市地标',
  attraction_category_name STRING COMMENT '景区类别名称',
  prd_id                   STRING COMMENT '产品ID',
  prd_name                 STRING COMMENT '产品名称',
  ticket_type              BIGINT COMMENT '票类型编码：1-景点门票 2-门票套餐 3-官方服务 4-研学体验 5-讲解服务 6-直通车 7-景点联票 8-项目体验 9-一日游 10-当地特色 11-跟团司导',
  ticket_type_name         STRING COMMENT '票类型名称',
  sales_channel_code       BIGINT COMMENT '购买渠道编码：1-携程 2-美团 3-飞猪 4-抖音团购 5-小红书 6-同程旅行 7-景区官网/小程序 8-线下窗口 9-旅行社分销',
  sales_channel_name       STRING COMMENT '购买渠道名称',
  order_time               STRING COMMENT '下单时间（YYYY-MM-DD HH:MM:SS）',
  visit_date               STRING COMMENT '游玩日期（YYYY-MM-DD）',
  booking_lead_day_qty     BIGINT COMMENT '提前预订天数',
  adult_qty                BIGINT COMMENT '成人票数',
  child_qty                BIGINT COMMENT '儿童票数',
  senior_qty               BIGINT COMMENT '长者票数',
  ticket_qty               BIGINT COMMENT '总票数',
  unit_price_amt           DOUBLE COMMENT '渠道成交单价（元）',
  original_amt             DOUBLE COMMENT '原价总额（元，门票类儿童/长者半价）',
  coupon_amt               DOUBLE COMMENT '优惠券金额（元）',
  paid_amt                 DOUBLE COMMENT '实付金额（元）=原价总额-优惠券金额',
  pay_method_type          BIGINT COMMENT '支付方式：1-微信支付 2-支付宝 3-银行卡 4-信用卡 5-花呗/分期',
  order_status             BIGINT COMMENT '订单状态编码：1-已核销 2-已退款 3-已过期未使用',
  order_status_name        STRING COMMENT '订单状态名称',
  refund_reason_type       BIGINT COMMENT '退款原因：0-无 1-天气原因 2-行程变更 3-价格原因 4-重复购买 5-临时有事',
  refund_amt               DOUBLE COMMENT '退款金额（元）',
  addon_prd_id             STRING COMMENT '园内加购产品ID（组合推荐真实转化，空=未加购）',
  addon_amt                DOUBLE COMMENT '加购金额（元）',
  secondary_spend_amt      DOUBLE COMMENT '园内二次消费金额（元）',
  secondary_spend_desc     STRING COMMENT '二次消费明细（项目:金额，以;分隔）',
  total_spend_amt          DOUBLE COMMENT '订单总消费（元）=实付+加购+二次消费，退款订单为0',
  review_rating_level      BIGINT COMMENT '游客评分（空=未评价）：1-很差 2-较差 3-一般 4-满意 5-非常满意',
  visit_weather_type       BIGINT COMMENT '游玩日天气编码：1-晴 2-多云 3-阴 4-雾霾 5-晴热高温 6-小雨 7-雷阵雨 8-中雨 9-大雨 10-小雪 11-中雪',
  visit_weather_name       STRING COMMENT '游玩日天气名称',
  visit_day_type           BIGINT COMMENT '游玩日日期类型编码：1-工作日 2-周末 3-法定节假日 4-调休工作日',
  visit_day_type_name      STRING COMMENT '游玩日日期类型名称',
  holiday_name             STRING COMMENT '法定节假日名称（非节假日为空）',
  traveler_segment_type    BIGINT COMMENT '出游客群：1-亲子游 2-情侣游 3-朋友结伴 4-独自旅行 5-银发游 6-家庭多代游 7-商务差旅 8-学生游',
  member_level             BIGINT COMMENT '下单时会员等级：1-普通会员 2-银卡 3-金卡 4-铂金卡'
)
COMMENT '景区门票订单明细天增量表：游客下单、支付、核销/退款与园内二次消费'
PARTITIONED BY (travel_date STRING COMMENT '分区日期，格式YYYYMMDD（游玩日期）')
STORED AS ORC;
