-- 景区日度客流与运营数据（辅助表）
CREATE TABLE IF NOT EXISTS dws.dws_opr_attraction_operation_di (
  stat_date                STRING COMMENT '统计日期（YYYY-MM-DD）',
  attraction_id            STRING COMMENT '景区ID（携程景区POI编号）',
  attraction_name          STRING COMMENT '景区名称',
  attraction_province_name STRING COMMENT '景区所在省份（由商品文本推断）',
  attraction_city_name     STRING COMMENT '景区所在城市（由商品文本推断）',
  attraction_category_type BIGINT COMMENT '景区类别编码：1-主题乐园 2-动物园/海洋馆 3-博物馆/展馆 4-演艺/秀场 5-温泉度假 6-古镇古村 7-宗教寺观 8-历史遗迹 9-滨海海岛 10-湖泊水域 11-山岳峡谷 12-自然生态 13-城市地标',
  attraction_category_name STRING COMMENT '景区类别名称',
  is_indoor                BIGINT COMMENT '是否室内景区：0-否 1-是',
  week_day_no              BIGINT COMMENT '星期：1-周一 2-周二 3-周三 4-周四 5-周五 6-周六 7-周日',
  day_type                 BIGINT COMMENT '日期类型编码：1-工作日 2-周末 3-法定节假日 4-调休工作日',
  day_type_name            STRING COMMENT '日期类型名称',
  holiday_name             STRING COMMENT '法定节假日名称（国务院放假安排，非节假日为空）',
  school_holiday_type      BIGINT COMMENT '寒暑假：0-非寒暑假 1-寒假 2-暑假',
  season_type              BIGINT COMMENT '业务季节：1-平季 2-暑期旺季 3-冬季淡季 4-春秋旺季 5-秋季旺季 6-寒假平季 7-春节黄金周 8-国庆黄金周 9-五一小长假 10-清明节小长假 11-端午节小长假 12-中秋节小长假 13-元旦小长假',
  weather_type             BIGINT COMMENT '天气编码：1-晴 2-多云 3-阴 4-雾霾 5-晴热高温 6-小雨 7-雷阵雨 8-中雨 9-大雨 10-小雪 11-中雪',
  weather_name             STRING COMMENT '天气名称',
  high_temperature         BIGINT COMMENT '最高气温（摄氏度）',
  low_temperature          BIGINT COMMENT '最低气温（摄氏度）',
  event_name               STRING COMMENT '节庆活动名称（无活动为空）',
  base_prd_id              STRING COMMENT '基础门票产品ID',
  list_price_amt           DOUBLE COMMENT '门票标价（元）',
  executed_price_amt       DOUBLE COMMENT '当日执行票价（元）',
  competitor_avg_price_amt DOUBLE COMMENT '周边竞品均价（元）',
  daily_capacity_qty       BIGINT COMMENT '日最大承载量（人）',
  traveler_qty             BIGINT COMMENT '实际入园人数',
  load_rate                DOUBLE COMMENT '承载率=入园人数/日最大承载量',
  is_sold_out              BIGINT COMMENT '是否满载：0-否 1-是',
  online_booking_qty       BIGINT COMMENT '线上预约入园人数',
  offline_traveler_qty     BIGINT COMMENT '线下购票入园人数',
  booked_d7_qty            BIGINT COMMENT '截至游玩日前7天累计线上预约人数',
  booked_d3_qty            BIGINT COMMENT '截至游玩日前3天累计线上预约人数',
  booked_d1_qty            BIGINT COMMENT '截至游玩日前1天累计线上预约人数',
  refund_order_qty         BIGINT COMMENT '退款订单量',
  ticket_revenue_amt       DOUBLE COMMENT '门票收入（元）',
  secondary_revenue_amt    DOUBLE COMMENT '二次消费收入（元）',
  total_revenue_amt        DOUBLE COMMENT '总收入（元）=门票收入+二次消费收入',
  avg_spend_amt            DOUBLE COMMENT '人均消费（元）',
  marketing_spend_amt      DOUBLE COMMENT '营销费用（元）',
  satisfaction_score       DOUBLE COMMENT '满意度均分（1-5）',
  complaint_qty            BIGINT COMMENT '投诉量'
)
COMMENT '景区日运营汇总天增量表：274个核心景区每日客流、预约进度、票价、收入、满意度及日历天气特征'
PARTITIONED BY (travel_date STRING COMMENT '分区日期，格式YYYYMMDD（统计日期）')
STORED AS ORC;
