-- 景区分销渠道数据集
CREATE TABLE IF NOT EXISTS dws.dws_trf_attraction_channel_sales_mo (
  stat_month               STRING COMMENT '统计月份（YYYY-MM）',
  attraction_id            STRING COMMENT '景区ID（携程景区POI编号）',
  attraction_name          STRING COMMENT '景区名称',
  attraction_province_name STRING COMMENT '景区所在省份（由商品文本推断）',
  attraction_city_name     STRING COMMENT '景区所在城市（由商品文本推断）',
  attraction_category_type BIGINT COMMENT '景区类别编码：1-主题乐园 2-动物园/海洋馆 3-博物馆/展馆 4-演艺/秀场 5-温泉度假 6-古镇古村 7-宗教寺观 8-历史遗迹 9-滨海海岛 10-湖泊水域 11-山岳峡谷 12-自然生态 13-城市地标',
  attraction_category_name STRING COMMENT '景区类别名称',
  prd_id                   STRING COMMENT '产品ID',
  prd_name                 STRING COMMENT '产品名称',
  ticket_type              BIGINT COMMENT '票类型编码：1-景点门票 2-门票套餐 3-官方服务 4-研学体验 5-讲解服务 6-直通车 7-景点联票 8-项目体验 9-一日游 10-当地特色 11-跟团司导',
  ticket_type_name         STRING COMMENT '票类型名称',
  sales_channel_code       BIGINT COMMENT '销售渠道编码：1-携程 2-美团 3-飞猪 4-抖音团购 5-小红书 6-同程旅行 7-景区官网/小程序 8-线下窗口 9-旅行社分销',
  sales_channel_name       STRING COMMENT '销售渠道名称',
  sales_channel_type       BIGINT COMMENT '渠道类型：1-OTA 2-内容电商 3-内容种草 4-自营直销 5-线下 6-B2B分销',
  list_price_amt           DOUBLE COMMENT '产品标价（元）',
  channel_price_amt        DOUBLE COMMENT '渠道售价（元）',
  commission_rate          DOUBLE COMMENT '渠道佣金率（0-1）',
  exposure_qty             BIGINT COMMENT '曝光量（线下窗口/旅行社分销为空）',
  click_qty                BIGINT COMMENT '点击量',
  click_rate               DOUBLE COMMENT '点击率=点击量/曝光量',
  order_qty                BIGINT COMMENT '订单量',
  conversion_rate          DOUBLE COMMENT '转化率=订单量/点击量',
  ticket_sold_qty          BIGINT COMMENT '售票张数',
  gmv_amt                  DOUBLE COMMENT '成交总额GMV（元）',
  commission_amt           DOUBLE COMMENT '佣金金额（元）',
  refund_order_qty         BIGINT COMMENT '退款订单量',
  refund_rate              DOUBLE COMMENT '退款率=退款订单量/订单量',
  net_revenue_amt          DOUBLE COMMENT '扣佣净收入（元）',
  marketing_spend_amt      DOUBLE COMMENT '营销投放费用（元）',
  roas_rate                DOUBLE COMMENT '投放回报率ROAS=GMV/营销投放费用',
  cpa_amt                  DOUBLE COMMENT '单订单获客成本（元）',
  new_customer_rate        DOUBLE COMMENT '新客占比（0-1）',
  avg_booking_lead_day_qty DOUBLE COMMENT '平均提前预订天数',
  main_segment_type        BIGINT COMMENT '主力客群：1-亲子游 2-情侣游 3-朋友结伴 4-独自旅行 5-银发游 6-家庭多代游 7-商务差旅 8-学生游',
  segment_family_rate      DOUBLE COMMENT '亲子游客群占比（0-1）',
  segment_couple_rate      DOUBLE COMMENT '情侣游客群占比（0-1）',
  segment_friends_rate     DOUBLE COMMENT '朋友结伴客群占比（0-1）',
  segment_solo_rate        DOUBLE COMMENT '独自旅行客群占比（0-1）',
  segment_senior_rate      DOUBLE COMMENT '银发游客群占比（0-1）',
  segment_multigen_rate    DOUBLE COMMENT '家庭多代游客群占比（0-1）',
  segment_business_rate    DOUBLE COMMENT '商务差旅客群占比（0-1）',
  segment_student_rate     DOUBLE COMMENT '学生游客群占比（0-1）'
)
COMMENT '景区产品分渠道销售月汇总表：统计月×景区×产品×渠道的曝光、转化、销售、佣金、投放与客群结构'
PARTITIONED BY (travel_date STRING COMMENT '分区日期，格式YYYYMMDD（统计月份首日）')
STORED AS ORC;
